### ISSUE TITLE
Please update example as current example provides parse error

### ISSUE THREAD

**Issue by layer3switch** [ioflo/ioflo#25]
As shown in README.md, the example produces "ParseError".

```
$ ioflo -V
1.6.5
$ pip show ioflo
Name: ioflo
Version: 1.6.5
Location: /usr/lib/python2.7/site-packages
Requires:

$ ioflo -v terse -f box1.flo

----------------------
Building Skeddar 'skedder' ...
Building Houses for Skedder 'skedder' ...
   Created House 'box1'. Assigning registries and creating instances ...
   Built House 'box1' with meta:
       name: Share(name=meta.name, data=Data([('value', 'skedder')]), deck=Deck([]))
       period: Share(name=meta.period, data=Data([('value', 0.125)]), deck=Deck([]))
       real: Share(name=meta.real, data=Data([('value', False)]), deck=Deck([]))
       mode: Share(name=meta.mode, data=Data([('value', [])]), deck=Deck([]))
       plan: Share(name=meta.plan, data=Data([('value', 'box1.flo')]), deck=Deck([]))
       filepath: Share(name=meta.filepath, data=Data([('value', '/repo/github.com/ioflo/box1.flo')]), deck=Deck([]))
       behaviors: Share(name=meta.behaviors, data=Data([('value', [])]), deck=Deck([]))
       credentials: Share(name=meta.credentials, data=Data([('username', ''), ('password', '')]), deck=Deck([]))
       failure: Share(name=meta.failure, data=Data([('value', '')]), deck=Deck([]))
       framers: Share(name=meta.framers, data=Data([]), deck=Deck([]))
       taskables: Share(name=meta.taskables, data=Data([('value', oset())]), deck=Deck([]))
       house: Share(name=meta.house, data=Data([('value', 'box1')]), deck=Deck([]))
   Built House 'box1' with preload:
       ioflo.version: Share(name=ioflo.version, data=Data([('value', '1.6.5')]), deck=Deck([]))
       ioflo.platform: Share(name=ioflo.platform, data=Data([('os', 'linux2'), ('python', '2.7.8')]), deck=Deck([]))

ParseError: Building verb 'set'. Unexpected connective 'to'. tokens = ['set', 'heading', 'to', '0.0'], index = 3.


Script line 13 in file /repo/github.com/ioflo/box1.flo
set heading to 0.0
Traceback (most recent call last):
  File "/bin/ioflo", line 36, in <module>
    main()
  File "/bin/ioflo", line 33, in main
    statistics=args.statistics)
  File "/usr/lib/python2.7/site-packages/ioflo/app/run.py", line 133, in run
    if skedder.build():
  File "/usr/lib/python2.7/site-packages/ioflo/base/skedding.py", line 210, in build
    if not b.build():
  File "/usr/lib/python2.7/site-packages/ioflo/base/building.py", line 472, in build
    if not self.dispatch(tokens):  # catches dispatches the return unexpectedly
  File "/usr/lib/python2.7/site-packages/ioflo/base/building.py", line 543, in dispatch
    return(getattr(self, verbMethod )(verb, tokens, index))
  File "/usr/lib/python2.7/site-packages/ioflo/base/building.py", line 2490, in buildSet
    raise excepting.ParseError(msg, tokens, index)
ioflo.base.excepting.ParseError: ParseError: Building verb 'set'. Unexpected connective 'to'. tokens = ['set', 'heading', 'to', '0.0'], index = 3.
```

**Comment by SmithSamuelM** [comment]
Fixed this. Thanks for pointing this out. Version 1.6 of ioflo changed syntax.
